<div class="bootstrap-wrapper">
    <form class="" id="form-consultar-cnpj">
        <div class="form-group">
            <label>CNPJ:</label>
            <input type="text" name="cnpj" value="" class="form-control cnpj" placeholder="CNPJ">
        </div>
        <button type="submit" class="btn btn-block btn-primary"><i class="fa fa-search"></i> Consultar</button>
        <div id="result" style="display:none;" class="mt-2"></div>
        <div id="loading" class="mt-3" style="display:none;">           
            <div class="alert alert-primary">
                <h3 class="p-0 m-0 text-center"> <i class="fa fa-cog fa-spin fa-fw"></i> Carregando</h3>
            </div>
        </div>
        <br>
        <span>Desenvolvido por <a href="https://consultarcnpj.com.br/" target="_blank">Consultarcnpj</a>.</span>
    </form>
</div>